---
description: Pipeline for GitLab audit events logs.
processors:
  - set:
      field: ecs.version
      value: '8.8.0'
  # Keep message as event.original.
  # Warn if event.original has already been set. This is most likely due to logstash ecs_compatibility setting.
  - append:
     if: ctx.event?.original != null
     field: error.message
     value: 'event.original is set before start of ingest pipeline'
  # keep message as event.original if it has not already been set.
  - rename:
      field: message
      target_field: event.original
      if: ctx.event?.original == null
  - json:
      field: event.original
      target_field: gitlab
  - script:
      description: Drops null/empty values recursively
      lang: painless
      source: |
        boolean drop(Object o) {
          if (o == null || o == "") {
            return true;
          } else if (o instanceof Map) {
            ((Map) o).values().removeIf(v -> drop(v));
            return (((Map) o).size() == 0);
          } else if (o instanceof List) {
            ((List) o).removeIf(v -> drop(v));
            return (((List) o).length == 0);
          }
          return false;
        }
        drop(ctx);
  - convert:
      field: gitlab.id
      target_field: _id
      type: string
      ignore_failure: true
      if: ctx?.gitlab?.uuid != null && ctx?.gitlab?.uuid != ""
  - date:
      field: gitlab.created_at
      formats:
        - ISO8601
      ignore_failure: true
  - set:
      field: event.kind
      value: event
      ignore_missing: true
      ignore_failure: true
  - convert:
      field: gitlab.id
      target_field: event.id
      type: string
      ignore_failure: true
  - set:
      field: user.id
      copy_from: gitlab.author_id
      ignore_missing: true
      ignore_failure: true
  - set:
      field: user.name
      copy_from: gitlab.author_name
      ignore_missing: true
      ignore_failure: true
  - set:
      field: source.ip
      copy_from: gitlab.ip_address
      ignore_missing: true
      ignore_failure: true
  - set:
      field: user.email
      copy_from: gitlab.author_email
      ignore_missing: true
      ignore_failure: true
  - rename:
      field: gitlab.change
      target_field: gitlab.change.field
      ignore_missing: true
      ignore_failure: true
  - rename:
      field: gitlab.from
      target_field: gitlab.change.from
      ignore_missing: true
      ignore_failure: true
  - rename:
      field: gitlab.to
      target_field: gitlab.change.to
      ignore_missing: true
      ignore_failure: true
  - remove:
      field: event.original
      if: "ctx?.tags == null || !(ctx.tags.contains('preserve_original_event'))"
      ignore_failure: true
      ignore_missing: true
on_failure:
  - set:
      field: event.kind
      value: pipeline_error
  - append:
      field: error.message
      value: >-
        Processor '{{ _ingest.on_failure_processor_type }}'
        {{#_ingest.on_failure_processor_tag}}with tag '{{ _ingest.on_failure_processor_tag }}'
        {{/_ingest.on_failure_processor_tag}}failed with message '{{ _ingest.on_failure_message }}'

